name: Fly Deploy
on:
  push:
    branches: [ "main" ]

concurrency:
  group: fly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_APP: your-app-name   # <-- set this
    steps:
      - uses: actions/checkout@v4

      # pick ONE of these:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      # - uses: superfly/flyctl-actions/setup-flyctl@1.5
      # - uses: superfly/flyctl-actions/setup-flyctl@master  # per README

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app "${FLY_APP}" --remote-only
