name: Fly Deploy

on:
  push:
    branches: [ "main" ]

concurrency:
  group: fly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_APP: your-app-name   # <-- set to your Fly app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v2

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            --app "${FLY_APP}" \
            --remote-only
