name: Fly Deploy
on:
  push:
    branches: [ "main" ]

concurrency:
  group: fly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_APP: your-app-name   # <-- set this
    steps:
      - uses: actions/checkout@v4

      # Use the setup action (recommended) — pin to a v1.x release
      - uses: superfly/flyctl-actions/setup-flyctl@v1.5
        # Optionally pin flyctl itself:
        # with:
        #   version: 0.3.180

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --app "${FLY_APP}" --remote-only
